"""ACP product feed — the discovery surface for agent commerce.

An ACP-compatible agent reads a product feed to learn what is purchasable. Here
the catalog is the digital credit-pack SKUs from :mod:`api.plans`. We expose it
two ways: served live at ``GET /acp/feed.json`` (absolute URLs resolved from the
request host) and as a committed static artifact (``acp/product_feed.json``,
generated by :func:`write_static_feed`) so the surface is version-controlled and
reviewable — nothing local-only.

ChatGPT Instant Checkout submission is deliberately out of scope (it is
physical-goods-only and application-gated); the feed is spec-faithful so any other
ACP agent can consume it today.
"""

from __future__ import annotations

import json
import os
from typing import Optional

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse

from api import plans

router = APIRouter(prefix="/acp", tags=["agentic-commerce"])

SELLER_NAME = "Universal Mail Automation"
TARGET_COUNTRIES = ["US"]
STORE_COUNTRY = "US"


def build_feed(base_url: str) -> dict:
    """Build the product feed for the given absolute base URL."""
    base = base_url.rstrip("/")
    products = []
    for pack in plans.CREDIT_PACKS.values():
        products.append({
            "item_id": pack["id"],
            "title": pack["title"],
            "description": (
                f"{pack['runs']} triage runs with a fail-closed protected-sender "
                "gate and a signed, independently verifiable audit receipt per run."
            ),
            "url": f"{base}/app/",
            "brand": SELLER_NAME,
            "image_url": f"{base}/app/",
            "price": pack["amount_cents"],
            "currency": "USD",
            "availability": "in_stock",
            "is_digital": True,
            "is_eligible_search": True,
            "is_eligible_checkout": True,
            "seller_name": SELLER_NAME,
            "seller_url": base,
            "target_countries": TARGET_COUNTRIES,
            "store_country": STORE_COUNTRY,
        })
    return {
        "version": "2026-04-17",
        "seller_name": SELLER_NAME,
        "checkout_url": f"{base}/acp/checkout_sessions",
        "products": products,
    }


@router.get("/feed.json")
async def feed(request: Request):
    return JSONResponse(build_feed(str(request.base_url)))


def write_static_feed(path: Optional[str] = None,
                      base_url: str = "https://mail.example.com") -> str:
    """Write the committed static feed artifact. Returns the path written."""
    path = path or os.path.join(os.path.dirname(__file__), "product_feed.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(build_feed(base_url), fh, indent=2)
        fh.write("\n")
    return path


if __name__ == "__main__":  # python -m acp.feed -> regenerate the static artifact
    print("wrote", write_static_feed())
